title: CCB
author:
  name: Charité Chor Berlin
  email: 'ccb-vorstand@gmx.de'
metadata:
    description: 'Im Charité Chor Berlin singen musikbegeisterte Studenten und Studentinnen verschiedener Fakultäten und Hochschulen, sowie einige junge Berufstätige.'
    robots: 'INDEX, FOLLOW'
    author: 'Charité Chor Berlin'
    keywords: 'Chor, Berlin, Studentenchor, Singen, Gesang, Studenten'
